---
- name: ensure flatpak software packages are installed
  ansible.builtin.package:
    pkg: "{{ item }}"
    state: present
  loop:
    - flatpak
  tags:
    - software
    - install
- name: Add the flathub flatpak remote to the system installation
  ansible.builtin.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
