---
# tasks file for software_development_package
- name: inlcude OS dependant variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: install vscode repo
  include_tasks: "tasks/vscode-repo.yml"
  tags:
    - software
    - install

- name: ensure developing software packages are installed
  package:
    pkg: "{{ development_package_software_packages }}"
    state: present
  tags:
    - software
    - install

- name: ensure developing software python packages are installed
  pip:
    name: "{{ item }}"
    state: latest
  loop: "{{ development_package_software_python_packages }}"
  tags:
    - software
    - install

- name: ensure developing software npm packages are installed
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
  loop: "{{ development_package_software_npm_packages }}"
  tags:
    - software
    - install

- name: install flatpak software
  include_tasks: "tasks/flatpak.yml"
  when: software_development_package_flatpak_software
  tags:
    - software
    - install
