---
# tasks file for software_development_package
- name: inlcude os dependant variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: install vscode repo
  ansible.builtin.include_tasks: "tasks/vscode-repo.yml"
  tags:
    - software
    - install

- name: ensure developing software packages are installed
  ansible.builtin.package:
    pkg: "{{ development_package_software_packages }}"
    state: present
  tags:
    - software
    - install

- name: ensure developing software python packages are installed
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop: "{{ development_package_software_python_packages }}"
  tags:
    - software
    - install

- name: ensure developing software npm packages are installed
  ansible.builtin.npm:
    name: "{{ item }}"
    state: present
    global: yes
  loop: "{{ development_package_software_npm_packages }}"
  tags:
    - software
    - install

- name: install flatpak software
  ansible.builtin.include_tasks: "tasks/flatpak.yml"
  when: software_development_package_flatpak_software
  tags:
    - software
    - install

- name: install snap software
  ansible.builtin.include_tasks: "tasks/snap.yml"
  when: software_development_package_snap_software
  tags:
    - software
    - install
