---

- name: Debian based distribution
  block:

  - name: install dependencies
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - python3-urllib3

  - name: import Microsoft key
    ansible.builtin.apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: present
      keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg

  - name: copy VS Code repo config
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
      state: present
      filename: vscode

  when: ansible_os_family == 'Debian'

- name: RedHat based distribution
  block:
  
  - name: import Microsoft key
    ansible.builtin.rpm_key:
      state: present
      key: "https://packages.microsoft.com/keys/microsoft.asc"
  
  - name: copy VS Code repo config
    ansible.builtin.copy:
      src: vscode.repo
      dest: /etc/yum.repos.d/vscode.repo
      owner: root
      group: root
      mode: "0644"
      
  when: ansible_os_family == 'RedHat'

