---
- name: import Microsoft key
  rpm_key:
    state: present
    key: "https://packages.microsoft.com/keys/microsoft.asc"
- name: copy VS Code repo config
  copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    owner: root
    group: root
    mode: "0644"
