---
dependency:
  name: galaxy
driver:
  name: podman
lint: 'yamllint'
platforms:
  - name: fedora32
    image: "geerlingguy/docker-fedora32-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
