---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora33
    image: "geerlingguy/docker-fedora33-ansible:latest"
    pre_build_image: true
  - name: fedora34
    image: "geerlingguy/docker-fedora34-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
